
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ackyras-Laptop
 */
public class DataAdmin extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs,rsb;
    String sql, ktp;
    /**
     * Creates new form DataAdmin
     */
    public DataAdmin(ResultSet rsd) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Konek db=new Konek();
        db.config();
        con =db.con;
        stat =db.stm;
        this.rs=rsd;
        try{
            setname(rs.getString("nama"));
            textnama.setText(rs.getString("nama"));
            textktp.setText(rs.getString("nomor ktp"));
            sql="select * from admin where `nomor ktp`= '"+rs.getString("nomor ktp")+"'";
            this.rsb=stat.executeQuery(sql);
            if(rsb.next()){
                texthp.setText(rsb.getString("nomor hp"));
            }
        }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void setname(String n){
        profil.setText(profil.getText()+n);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        textnama = new javax.swing.JTextField();
        textktp = new javax.swing.JTextField();
        texthp = new javax.swing.JTextField();
        textpw = new javax.swing.JPasswordField();
        j6 = new javax.swing.JLabel();
        textpw1 = new javax.swing.JPasswordField();
        prbaru = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        textjk = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setBackground(new java.awt.Color(227, 132, 1));
        j1.setForeground(new java.awt.Color(227, 132, 1));
        j1.setText("Nama                     :");
        jPanel2.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        j2.setBackground(new java.awt.Color(227, 132, 1));
        j2.setForeground(new java.awt.Color(227, 132, 1));
        j2.setText("Nomor KTP             :");
        jPanel2.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        j3.setBackground(new java.awt.Color(227, 132, 1));
        j3.setForeground(new java.awt.Color(227, 132, 1));
        j3.setText("Jenis Kelamin         :");
        jPanel2.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        j4.setBackground(new java.awt.Color(227, 132, 1));
        j4.setForeground(new java.awt.Color(227, 132, 1));
        j4.setText("Nomor HP               :");
        jPanel2.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        j5.setBackground(new java.awt.Color(227, 132, 1));
        j5.setForeground(new java.awt.Color(227, 132, 1));
        j5.setText("Password               :");
        jPanel2.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel2.add(textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 199, -1));
        jPanel2.add(textktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));
        jPanel2.add(texthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));
        jPanel2.add(textpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, -1));

        j6.setBackground(new java.awt.Color(227, 132, 1));
        j6.setForeground(new java.awt.Color(227, 132, 1));
        j6.setText("Ulangi Password    :");
        jPanel2.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 95, -1));
        jPanel2.add(textpw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, -1));

        prbaru.setText("Perbarui Profil Anda");
        prbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prbaruActionPerformed(evt);
            }
        });
        jPanel2.add(prbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 297, -1));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        textjk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        textjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjkActionPerformed(evt);
            }
        });
        jPanel2.add(textjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 330));

        jPanel4.setBackground(new java.awt.Color(227, 132, 1));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setText("Profil Admin Universitas Kace");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 290, 40));

        profil.setText("Data Admin ");
        jPanel4.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prbaruActionPerformed
        // TODO add your handling code here:
        try{
            sql = "UPDATE `admin` SET `Nama`='"+textnama.getText()+"',`Nomor KTP`='"+textktp.getText()+"',`Jenis kelamin`='"+textjk.getSelectedItem()+"',`Nomor HP`='"+texthp.getText()+"' WHERE `nomor ktp` ='"+
                    rs.getString("nomor ktp")+"'";
            stat.execute(sql);
            String pw;
            if(textpw1.getText()==null||textpw.getText()==null){
                JOptionPane.showMessageDialog(this, "Anda tidak mengganti password anda");
                pw=rs.getString("password");
            }else if(textpw1.getPassword()==textpw.getPassword()){
                pw=textpw1.getText();
            }
            sql="update akun set nama='"+textnama.getText()+"',`Nomor KTP`='"+textktp.getText()+"',password='"+textpw1.getText()+"' where `nomor ktp` ='"+
                    rs.getString("nomor ktp")+"'";
            stat.execute(sql);
            sql="select * from akun where `nomor ktp`='"+textktp.getText()+"'";
            rs=stat.executeQuery(sql);
            if(rs.next()){
                Adminframe ad = new Adminframe(rs);
                this.dispose();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }     
    }//GEN-LAST:event_prbaruActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Adminframe ad = new Adminframe(rs);
            ad.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(DataAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton prbaru;
    private javax.swing.JLabel profil;
    private javax.swing.JTextField texthp;
    private javax.swing.JComboBox textjk;
    private javax.swing.JTextField textktp;
    private javax.swing.JTextField textnama;
    private javax.swing.JPasswordField textpw;
    private javax.swing.JPasswordField textpw1;
    // End of variables declaration//GEN-END:variables
}
