
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ackyras-Laptop
 */
public class Mabaframe extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rsb,rs;
    String sql;
    /**
     * Creates new form Mabaframe
     */
    public Mabaframe(ResultSet rsd) throws SQLException {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        Konek db=new Konek();
        db.config();
        con =db.con;
        stat =db.stm;
        this.rs=rsd;
        profil.setText(profil.getText()+rs.getString("nama"));
        try{
            textnama.setText(rs.getString("nama"));
            textktp.setText(rs.getString("nomor ktp"));
            sql="select * from mahasiswa where `nomor ktp`= '"+rs.getString("nomor ktp")+"'";
            this.rsb=stat.executeQuery(sql);
            if(rsb.next()){texthp.setText(rsb.getString("nomor hp"));
                textnp.setText(rsb.getString("No. pendaftaran"));
                texttl.setText(rsb.getString("Tempat Lahir"));
                textttl.setText(rsb.getString("Tanggal Lahir"));
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        textnama = new javax.swing.JTextField();
        textktp = new javax.swing.JTextField();
        texthp = new javax.swing.JTextField();
        prbaru = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        textjk = new javax.swing.JComboBox();
        j7 = new javax.swing.JLabel();
        textnp = new javax.swing.JTextField();
        j8 = new javax.swing.JLabel();
        texttl = new javax.swing.JTextField();
        j9 = new javax.swing.JLabel();
        textttl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(227, 132, 1));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setText("Profil Maba Universitas Kace");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 290, 40));

        profil.setText("Mahasiswa Baru Universitas Kace \n hi ");
        jPanel4.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setBackground(new java.awt.Color(227, 132, 1));
        j1.setForeground(new java.awt.Color(227, 132, 1));
        j1.setText("Nama                       :");
        jPanel2.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        j2.setBackground(new java.awt.Color(227, 132, 1));
        j2.setForeground(new java.awt.Color(227, 132, 1));
        j2.setText("Nomor KTP              :");
        jPanel2.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        j3.setBackground(new java.awt.Color(227, 132, 1));
        j3.setForeground(new java.awt.Color(227, 132, 1));
        j3.setText("Jenis Kelamin           :");
        jPanel2.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        j4.setBackground(new java.awt.Color(227, 132, 1));
        j4.setForeground(new java.awt.Color(227, 132, 1));
        j4.setText("Nomor HP                :");
        jPanel2.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel2.add(textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 199, -1));
        jPanel2.add(textktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));
        jPanel2.add(texthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, -1));

        prbaru.setText("Perbarui Profil Anda");
        prbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prbaruActionPerformed(evt);
            }
        });
        jPanel2.add(prbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, -1));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        textjk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        textjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjkActionPerformed(evt);
            }
        });
        jPanel2.add(textjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, -1));

        j7.setBackground(new java.awt.Color(227, 132, 1));
        j7.setForeground(new java.awt.Color(227, 132, 1));
        j7.setText("Nomor Pendaftaran:");
        jPanel2.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel2.add(textnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 199, -1));

        j8.setBackground(new java.awt.Color(227, 132, 1));
        j8.setForeground(new java.awt.Color(227, 132, 1));
        j8.setText("Tempat Lahir           :");
        jPanel2.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel2.add(texttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 200, -1));

        j9.setBackground(new java.awt.Color(227, 132, 1));
        j9.setForeground(new java.awt.Color(227, 132, 1));
        j9.setText("Tanggal Lahir          :");
        jPanel2.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel2.add(textttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prbaruActionPerformed
        // TODO add your handling code here:
        try{
            
            if("1".equals(rsb.getString("validasi"))){
                int dialogButton=JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (null, "Akun Anda telah divalidasi, jika anda mengganti data Anda maka validasi anda akan diulang.\nUlangi?","Warning",dialogButton);
                if(dialogResult != JOptionPane.YES_OPTION){
                    Mabaframe ad = new Mabaframe(rs);
                    this.dispose();
                }
            }sql="update mahasiswa set validasi='0' where `no. pendaftaran`='"+rsb.getString("no. pendaftaran")+"'";
            stat.execute(sql);
            sql = "UPDATE `mahasiswa` SET `tanggal lahir`='"+textttl.getText()+"',`tempat lahir`='"+texttl.getText()+"', `no. pendaftaran`='"+textnp.getText()+"', `Nama`='"+textnama.getText()+"',`Nomor KTP`='"+textktp.getText()+"',`Jenis kelamin`='"+textjk.getSelectedItem()+"',`Nomor HP`='"+texthp.getText()+"' WHERE `nomor ktp` ='"+
            rs.getString("nomor ktp")+"'";
            stat.execute(sql);
            sql="update akun set nama='"+textnama.getText()+"',`Nomor KTP`='"+textktp.getText()+"' where `nomor ktp` ='"+
                    rs.getString("nomor ktp")+"'";
            stat.execute(sql);
            if(textttl.getText()!=null&&texttl.getText()!=null&&textnp.getText()!=null&&textnama.getText()!=null&&textktp.getText()==null&&rs.getString("Jenis kelamin")!=null&&texthp.getText()!=null){
                sql="update mahasiswa set lengkap='1'";
                JOptionPane.showMessageDialog(this, "Data Anda telah lengkap!");
            }
            sql="select * from akun where `nomor ktp`='"+textktp.getText()+"'";
            rs=stat.executeQuery(sql);
            if(rs.next()){
                Mabaframe ad = new Mabaframe(rs);
                this.dispose();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_prbaruActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Cek lagi data Anda","Yakin ingin keluar?",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Loginframe rf = new Loginframe();
                rf.setVisible(true);
                this.dispose();
            }         
        } catch (SQLException ex) {
            Logger.getLogger(DataAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mabaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mabaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mabaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mabaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton prbaru;
    private javax.swing.JLabel profil;
    private javax.swing.JTextField texthp;
    private javax.swing.JComboBox textjk;
    private javax.swing.JTextField textktp;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textnp;
    private javax.swing.JTextField texttl;
    private javax.swing.JTextField textttl;
    // End of variables declaration//GEN-END:variables
}
